app = "codeacademy-api"
primary_region = "iad"

[build]
  image = "registry.fly.io/codeacademy-api:latest"

[env]
  RUNNER_URL = "http://runner-host-or-ip:8001"
  API_KEY = "change-me"

[[services]]
  internal_port = 8001
  protocol = "tcp"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    handlers = ["http"]
    port = 80
